/*
 * The User API
 *
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.8 indivisible-esau
 * Contact: dev@lab5e.com
 * Generated by: https://openapi-generator.tech
 */

/// InviteList : List of active invites. Onece an invite has been redeemed it will be removed automatically. An administrator of the team can delete unused invites.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteList {
    #[serde(rename = "invites", skip_serializing_if = "Option::is_none")]
    pub invites: Option<Vec<crate::models::Invite>>,
}

impl InviteList {
    /// List of active invites. Onece an invite has been redeemed it will be removed automatically. An administrator of the team can delete unused invites.
    pub fn new() -> InviteList {
        InviteList { invites: None }
    }
}
